# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poll_name',
            new_name='poll_num',
        ),
    ]
