# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20161031_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=256, verbose_name=b'column_name'),
        ),
    ]
